---
- name: install dropbox for Ubuntu family
  include: "Ubuntu.yml"
  when: ansible_distribution == 'Ubuntu'
  tags: ["packages","dropbox"]

- name: install dropbox for Fedora family
  include: "Fedora.yml"
  when: ansible_distribution == 'Fedora'
  tags: ["packages","dropbox"]
