---

- name: Install Chrome for Ubuntu family
  include: "ubuntu.yml"
  when: ansible_distribution == 'Ubuntu'
  tags: [ "packages", "chrome" ]

- name: Install Chrome for Fedora family
  include: "fedora.yml"
  when: ansible_distribution == 'Fedora'
  tags: [ "packages", "chrome" ]
