---
- name: Check if Chrome is already installed
  stat:
    path: /usr/bin/google-chrome
  register: chrome_binary

- name: Download Ubuntu Google Chrome package
  get_url: url={{chrome_url_ubuntu_deb}} dest={{chrome_tmp_deb}}
  when: not chrome_binary.stat.exists

- name: Install Ubuntu Google Chrome package
  apt: deb={{chrome_tmp_deb}}
  sudo: yes
  when: not chrome_binary.stat.exists
